server:
  port: 8900

spring:
  application:
    name: demo-monitor
  security: # 配置登录用户名和密码
    user:
      name: admin
      password: 123456
  boot:  # 不显示admin-security-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}

eureka:
  client:
    register-with-eureka: true # false 表示不需要向注册中心注册自己
    fetch-registry: true # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://admin:123456@localhost:8800/eureka/