server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://47.52.162.110:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.liucccc.demo.dao.entity